### ISSUE TITLE
Are constant Node updates essential?

### ISSUE THREAD

**Issue by OfficialKaos** [ebaauw/homebridge-zp#123] opened 2020-01-12 16:58 UTC
@ebaauw Thanks for an amazing plugin

I've been using it for several months maybe a year now and my question is why do you keep updating the Node version requirement for it?

Reason I ask is I use HOOBS and to update the Node version isn't always easy or straight forward.

Also do I need to update my version everytime you do? 
Apart from it indicating to me in the log it's the wrong version of Node it seems to work perfect!?

Currently I'm using Node 12.4.0

**Comment by ebaauw** [comment] 2020-01-12 18:09
I develop and test against the latest LTS release of NodeJS.  They usually include security patches in these releases, so I strongly recommend to upgrade when a new version comes out.

Other versions of NodeJS might very well work, but sometimes they don’t.  I’d rather spend my personal time on new functionalities than testing against other versions.

**Comment by BobbySlope** [comment] 2020-01-12 18:32
The point is that most of the plugins dint work at the newest LTS right now, because other developers dont maintain their pluginsas well as you do :)
So update node to latest LTS causing issues with other plugins that arent ready for the latest LTS

**Comment by ebaauw** [comment] 2020-01-12 18:57
And how is this my problem?

I certainly don’t recommend to run whatever plugins you can find together in a single homebridge instance, on a single (virtual) machine.  Nobody is forcing you to upgrade any of my plugins when I release a new version.  I do supply release notes with each version, so you know any changed dependencies before upgrading.

**Comment by OfficialKaos** [comment] 2020-01-12 19:47
Just saying that if you keep changing the necessary Node version for your plugin, the users of your plugin keep encountering issues with the upgrade process.. So why complicate things anymore than you need to for us? 
And also I am only using this plugin in a single homebridge instance, so I can only imagine what others must be suffering! just saying..

**Comment by ebaauw** [comment] 2020-01-12 20:22
Again, how is this my problem?

I've worked too long in IT to think that I can get away with outdated software, but, hey, that's just my thing.  I don't provide any service to any-one, and I don't receive any compensation for my plugins.  I just publish the plugins I develop (in my own time!) as-is, for my own use and for the benefit of fellow developers.  You're free to use them however you see fit.  If you don't like them, don't use them, or create your own fork.  If you think you're "suffering" too much upgrading them, don't upgrade them.

**Comment by BobbySlope** [comment] 2020-01-12 20:29
@OfficialKaos as @ebaauw mentioned above we just forked the plugin, we will make an certified version compatible with HOOBS

**Comment by OfficialKaos** [comment] 2020-01-12 20:34
That'll be great , thank you 👍

**Comment by BobbySlope** [comment] 2020-01-12 20:39
Heres our Projectboard where you can follow the Progress: [Certified Plugins](https://github.com/hoobs-org/HOOBS/projects/6)
So you can close this Issue

**Closed** 2020-01-12 20:52 UTC
Labels: question

**Comment by mkellsy** [comment] 2020-01-12 23:40
Node 10 is still supported. It was updated to version 10.18.0 last week.

And since Node is updated weekly sometimes, especially around LTS release time you can save yourself some headaches by waiting 6 months for them to iron things out.

I don't work in IT, bit I am. Senior Software Engineer and have been for the past 10 years. If our IT department wants to teardown servers, VMs and containers just to update Node once a week, they better have the compliance documents, systems testing results and regression testing results in place before doing it. And a document explaining why the upgrade is required and what are the alternatives.

Our developers have been developing on the latest for years so the code is covered and unit tests passed.

Now do this on a weekly basis. Not feasible. If upgrading Node weekly is not feasible for a SaaS company, with many "paid" employees, how can you expect a "non paid" hobbyist to do the same.

We are not asking you to change your testing. We are not asking you to use outdated software. We are just asking you to keep the node requirement on the last LTS and give people time to update their systems on their own schedule.

**Comment by ebaauw** [comment] 2020-01-13 08:54
> We are just asking you to keep the node requirement on the last LTS

That's exactly what I'm doing.  I only upgraded from NodeJS v10.x to NodeJS v12.x when v12.x entered LTS state, in Oct 2019.  I expect to be moving to v14.x around Oct/Nov 2020, see https://nodejs.org/en/about/releases/.

**Comment by mkellsy** [comment] 2020-01-13 09:50
And Node 10x is LTS active until April 2020.
