### ISSUE TITLE
bad wifi connection - constantly new accessory

### ISSUE THREAD

**Issue by nicoh88** [ebaauw/homebridge-zp#52] opened 2018-10-09 08:35 UTC
Hello @ebaauw,

i have a little problem with `homebridge-zp`. I have two Sonos Play:1 speakers, one in the living room and one in the bathroom. The bathroom has often times disconnects, due to weak Wi-Fi. 👎 

```
{
"platform": "ZP",
 "service": "switch",
 "brightness": true,
 "speakers": true
},
```

I think, always, if the WLAN causes problems, HomeKit always get two new characteristics for the bathroom (Sonos + Multiroom) - the old characteristics are deleted. Room assignments are lost, settings in favorites and status also.

Can the problem be solved? So, Sonos Play: 1 in the bathroom is not always recognized as a new speaker?

Cheers 👋 
Nico

**Comment by ebaauw** [comment] 2018-10-09 12:55
> I think, always, if the WLAN causes problems ... Room assignments are lost, settings in favorites and status also.

This cannot be caused by WLAN problems alone.  Losing room assignments, etc, only happens when the accessory is removed from HomeKit and then re-added, causing HomeKit to treat it as a new accessory.  To remove the accessory from HomeKit, you would have to restart homebridge while the bathroom sonos cannot be reached, so homebridge-zp starts only exposing the living room sonos.  Then you would have to restart homebridge again, and this time homebridge-zp must find the bathroom sonos, so it's exposed again (and seen as a new accessory by HomeKit).

You might try and set `"searchTimeout": 15` in config.json, to give homebridge-zp some more time to find the sonos players on startup. The default of 5 seconds is sometimes not enough in my network, so I use this setting.

**Comment by nicoh88** [comment] 2018-10-11 07:32
It looks good - since 2 days no problems. I'll get back in 5 days. 👍

**Comment by ebaauw** [comment] 2018-10-21 19:44
Closing this issue.  Please re-open if there's still problems.

**Closed by ebaauw** 2018-10-21 19:44 UTC
Labels: question

**Comment by nicoh88** [comment] 2018-10-23 09:18
Unfortunately, the problem with `searchTimeout` has not been resolved. I have now added a new wlan repeater to solve the wireless problemes in the bathroom. Today, was the Play:1 in the livingroom removed and new added in HomeKit - a other wlan repeater is 3 meters away. 😢

**Everything is quite strange.**

I have now set journald logging to `persistent` and will report again. Whether at the time of restarting Homebridge or in case of a crash, the sonos player is really unreachable / disconnected.

Kind regards,
Nico

**Comment by ebaauw** [comment] 2018-10-23 11:06
Do you connect each Sonos player to your WiFi network separately, or do you use the Sonos WiFi mesh network?  I find that in my case, using the Sonos mesh is far more reliable.

**Comment by nicoh88** [comment] 2018-10-25 08:40
Hi @ebaauw,

i use my own WiFI network. I needed, for my music library on my Samba- / Windows-File-Share. 👎

**Comment by nicoh88** [comment] 2018-10-27 12:54
Hi @ebaauw,

you're right, if homebridge crashes (shit logitech harmony plugin) or reboots and the sonos player was not found, it will be added next time as a new accessory.

Homebridge crash, automatically restart without sonos player at bathroom (Bad):

```
Oct 27 09:04:10 rpi-smarthome homebridge[28888]: [2018-10-27 09:04:10] [ZP] warning: lastest version: homebridge-zp v0.2.35
Oct 27 09:04:10 rpi-smarthome homebridge[28888]: [2018-10-27 09:04:10] [ZP] Wohnzimmer: setup ZPS12 v9.2 player RINCON_949F3E027C8E01400 at 192.168.137.41:1400
Oct 27 09:04:10 rpi-smarthome homebridge[28888]: [2018-10-27 09:04:10] [Staubsauger EG Flur] Firmwareversion: 3.3.9_001518
...
Oct 27 09:04:12 rpi-smarthome homebridge[28888]: [2018-10-27 09:04:12] [Harmony Hub] Found activities:
Oct 27 09:04:12 rpi-smarthome homebridge[28888]:         PowerOff
Oct 27 09:04:12 rpi-smarthome homebridge[28888]:         Media Center
Oct 27 09:04:12 rpi-smarthome homebridge[28888]:         PlayStation 4
Oct 27 09:04:23 rpi-smarthome homebridge[28888]: [2018-10-27 09:04:23] [ZP] listening on http://192.168.137.65:44589/notify
Oct 27 09:04:23 rpi-smarthome homebridge[28888]: [2018-10-27 09:04:23] [ZP] Wohnzimmer Sonos: SUBSCRIBE http://192.168.137.41:1400/GroupManagement/Event
Oct 27 09:04:23 rpi-smarthome homebridge[28888]: [2018-10-27 09:04:23] [ZP] Initializing platform accessory 'Wohnzimmer Sonos'...
Oct 27 09:04:23 rpi-smarthome homebridge[28888]: Setup Payload:
...
```

Next homebridge restart with both sonos player (Bad, Wohnzimmer):

```
...
Oct 27 09:32:27 rpi-smarthome homebridge[3558]: [2018-10-27 09:32:27] [ZP] warning: lastest version: homebridge-zp v0.2.35
Oct 27 09:32:27 rpi-smarthome homebridge[3558]: [2018-10-27 09:32:27] [Staubsauger EG Flur] Firmwareversion: 3.3.9_001518
Oct 27 09:32:27 rpi-smarthome homebridge[3558]: [2018-10-27 09:32:27] [ZP] Bad: setup ZPS12 v9.2 player RINCON_949F3E027CE401400 at 192.168.137.40:1400
Oct 27 09:32:27 rpi-smarthome homebridge[3558]: [2018-10-27 09:32:27] [ZP] Wohnzimmer: setup ZPS12 v9.2 player RINCON_949F3E027C8E01400 at 192.168.137.41:1400
...
Oct 27 09:32:30 rpi-smarthome homebridge[3558]: [2018-10-27 09:32:30] [Harmony Hub] Found activities:
Oct 27 09:32:30 rpi-smarthome homebridge[3558]:         PowerOff
Oct 27 09:32:30 rpi-smarthome homebridge[3558]:         Media Center
Oct 27 09:32:30 rpi-smarthome homebridge[3558]:         PlayStation 4
Oct 27 09:32:40 rpi-smarthome homebridge[3558]: [2018-10-27 09:32:40] [ZP] listening on http://192.168.137.65:42707/notify
Oct 27 09:32:40 rpi-smarthome homebridge[3558]: [2018-10-27 09:32:40] [ZP] Bad Sonos: SUBSCRIBE http://192.168.137.40:1400/GroupManagement/Event
Oct 27 09:32:40 rpi-smarthome homebridge[3558]: [2018-10-27 09:32:40] [ZP] Wohnzimmer Sonos: SUBSCRIBE http://192.168.137.41:1400/GroupManagement/Event
Oct 27 09:32:40 rpi-smarthome homebridge[3558]: [2018-10-27 09:32:40] [ZP] Initializing platform accessory 'Bad Sonos'...
Oct 27 09:32:40 rpi-smarthome homebridge[3558]: [2018-10-27 09:32:40] [ZP] Initializing platform accessory 'Wohnzimmer Sonos'...
Oct 27 09:32:40 rpi-smarthome homebridge[3558]: Setup Payload:
...
```

The bad Wi-Fi connection should not be there, the problem I have fixed. 👍 
I set now the `searchTimeout` to `30`.

**Comment by nicoh88** [comment] 2018-10-30 12:46
Hi @ebaauw,

`searchTimeout` to `30` brought no improvement. 😢 

According to my nagios monitoring the sonos speaker in the bathroom was still hard to reach. (ping) I restart my two sonos speaker 3 days ago, since then no disconnections and no new accessory in HomeKit.

I've written a bash script that automatically reboots my speakers once a week.
https://github.com/nicoh88/cron_sonos-reboot
